on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Publish Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Testing
        run: npm test
      - name: docs generation
        run: npm run mddocs
      - name: docs upload
        run: npm run docs
      - name: CodeCoverage
        run: npx codecov
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Wait sonar to process report
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Commit docs and tagging
        run: |
          echo "::set-env name=TRAVIS_BRANCH::${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}"
          ./commit_tag_push.sh
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          TRAVIS_BRANCH: ${{ github.head_ref }}
          CONNECT_GITHUB_TOKEN: ${{ secrets.CONNECT_GITHUB_TOKEN }}
      - name: Publish NPM package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          dry-run: false
          check-version: true
